version: '2.1'
# Use for production

version: '2'
services:
  express-rest-api:
    build:
      context: .
    volumes:
      # Mounts the project directory on the host to /app inside the container,
      # allowing you to modify the code without having to rebuild the image.
      - '.:/app'
      # Just specify a path and let the Engine create a volume.
      # Data present in the base image at the specified mount point will be copied
      # over to the new volume upon volume initialization.
      # node_modules from this new volume will be used and not from your local dev env.
      - /app/node_modules/
    # Expose ports [HOST:CONTAINER}
    ports:
      - '3000:3000'
    # Set environment variables from this file
    env_file:
      - prod.env
networks:
  default:
    external:
      name: 127.0.0.1
