version: '2'

services:
  express: #name of the second service
    build: . # specify the directory of the Dockerfile
    volumes:  #local env to make database usable
      - '.:/app'
      - /app/node_modules/
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database #link to database
  database:
    image: mongo
    ports:
      - "27017:27017"
